version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: condoconect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: backend-image:latest
    build:
      context: ./back-tesis
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
